---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsqd.admin.fullname" . }}
  labels:
    service: admin
{{ include "nsqd.labels" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 4171
      protocol: TCP
      targetPort: 4171
  selector:
    service: admin
    app.kubernetes.io/name: {{ include "nsqd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
