---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsqd.nsqd.fullname" . }}
  labels:
    service: nsqd
{{ include "nsqd.labels" . | indent 4 }}
spec:
  ports:
    - name: tcp
      port: 4150
      protocol: TCP
      targetPort: 4150
    - name: http
      port: 4151
      protocol: TCP
      targetPort: 4151
  selector:
    service: nsqd
    app.kubernetes.io/name: {{ include "nsqd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
