stages:
  - start
  - deploy
  - post
variables:
  DOCKER_COMPOSE_PROJECT: ${CI_COMMIT_REF_SLUG}-${CI_JOB_ID}

before_script:
  - rm /home/gitlab-runner/.docker/config.json || true
  - docker-compose -p ${CI_COMMIT_REF_SLUG}-${CI_JOB_ID} down -v

k3s_helm3:
  stage: start
  variables:
    DK: docker-compose -p ${CI_COMMIT_REF_SLUG}-${CI_JOB_ID}
    DR: docker-compose -p ${CI_COMMIT_REF_SLUG}-${CI_JOB_ID} run client
  script:
    - ${DK} pull
    - ${DK} up -d server
    - sleep 10
    - ${DR} kubectl apply -f overlays/k3s/volumes
    - ${DR} kubectl label nodes --all pool=default
    - ${DR} helm3 upgrade --wait --timeout 1200s --install --debug --atomic noc noc --set image.tag=master-dev --set image.pullPolicy=Always
  tags:
    - shell
  artifacts:
    paths:
      - kubeconfig.yaml
    expire_in: 1 hours

after_script:
  - docker-compose -p ${CI_COMMIT_REF_SLUG}-${CI_JOB_ID} down -v
