stages:
  - start
  - deploy
  - post
variables:
  DOCKER_COMPOSE_PROJECT: ${CI_COMMIT_REF_SLUG}-${CI_JOB_ID}

Start K3S:
  stage: start
  variables:
    DK: docker-compose -p ${CI_COMMIT_REF_SLUG}-${CI_JOB_ID}
    DR: ${DK} run client
  script:
    - ${DK} pull
    - ${DK} up -d server
    - sleep 10
    - ${DR} kubectl apply -f overlays/k3s/volumes
    - ${DR} kubectl apply -f tiller.yaml
    - ${DR} helm init --service-account tiller --history-max 1 --upgrade --wait
    - ${DR} helm upgrade --wait --install --atomic noc noc/
  tags:
    - shell
  artifacts:
    paths:
      - kubeconfig.yaml
    expire_in: 1 hours

after_script:
  - docker-compose -p ${CI_COMMIT_REF_SLUG}-${CI_JOB_ID} down -v
