---
apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  ports:
  - protocol: TCP
    port: 8500
    targetPort: 8500
---
apiVersion: v1
kind: Endpoints
metadata:
  name: consul
subsets:
  - addresses:
      - ip: 192.0.2.1  # example ip
    ports:
      - port: 8500
