---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-db-init"
  labels:
{{ include "noc.labels" . | indent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    "helm.sh/hook-weight": "10"
spec:
  template:
    spec:
      containers:
        - command:
            - "sh"
            - "-c"
            - >
              set -xe
              && /usr/bin/python ./commands/migrate.py
              && /usr/bin/python ./scripts/deploy/apply-pools
              && ./noc ensure-indexes
              && /usr/bin/python ./commands/migrate-ch.py
              && /usr/bin/python ./scripts/deploy/install-packages requirements/collections.json
              && ./noc collection sync
              && ./noc sync-perm
              && ./noc sync-mibs
          env:
            - name: NOC_PATH_NPKG_ROOT
              value: /tmp
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-noc-configmap
            - secretRef:
                name: {{ .Release.Name }}-noc-secret
            - secretRef:
                name: {{ .Release.Name }}-noc-init-admin-secret
          image: "{{ .Values.image.repository }}/code:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: db-init
          resources:
            limits:
              cpu: 1
              memory: 250Mi
            requests:
              cpu: 1
              memory: 250Mi
          securityContext:
            runAsUser: 1200
          volumeMounts:
            - mountPath: /opt/noc/etc/
              name: pool-config
      volumes:
        - name: pool-config
          configMap:
            name: {{ .Release.Name }}-pool-configmap
      restartPolicy: Never
    {{- if .Values.rbac.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
    {{- end}}
