apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "admin.fullname" . }}
  labels:
    app: {{ template "admin.name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "admin.name" . }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: component
                    operator: In
                    values:
                      - nsqadmin
                  - key: app
                    operator: In
                    values:
                      - nsq
              topologyKey: kubernetes.io/hostname
      containers:
      - name: {{ template "admin.name" . }}
        image: {{ template "nsq.image" . }}
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
        resources:
{{ toYaml .Values.admin.resources | indent 10 }}
        command:
          - /nsqadmin
          {{- range $i, $v := until (int .Values.lookupd.replicas) }}
          - -lookupd-http-address
          - nsq-lookupd-{{$i}}.nsq-lookupd:4161
          {{- end }}
        ports:
        - name: http
          containerPort: 4171
