apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "lookupd.fullname" . }}
  labels:
    app: {{ template "lookupd.name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "lookupd.name" . }}
      component: nsqlookupd
  serviceName: "nsqlookupd"
  replicas: {{ .Values.lookupd.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "lookupd.name" . }}
        component: nsqlookupd
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                      - nsqlookupd
                  - key: app
                    operator: In
                    values:
                      - nsq
                topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 5
      containers:
      - name: nsqlookupd
        image: {{ template "nsq.image" . }}
        imagePullPolicy: Always
        resources:
{{ toYaml .Values.lookupd.resources | indent 10 }}
        command:
        - /nsqlookupd
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 2
        ports:
        - name: tcp
          containerPort: 4160
        - name: http
          containerPort: 4161
