apiVersion: v1
kind: Service
metadata:
  name: {{ template "lookupd.fullname" . }}
  labels:
    app: {{ template "lookupd.name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - port: 4160
    protocol: TCP
    name: tcp
    targetPort: 4160
  - port: 4161
    protocol: TCP
    name: http
    targetPort: 4161
  selector:
    app: {{ template "lookupd.name" . }}
