apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "nsqd.fullname" . }}
  labels:
    app: {{ template "nsqd.name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "nsqd.name" . }}
      component: nsqd
  serviceName: "nsqd"
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "nsqd.name" . }}
        component: nsqd
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9117'
    spec:
      containers:
      - name: nsqd
        image: {{ template "nsq.image" . }}
        volumeMounts:
        - name: datadir
          mountPath: /data
        resources:
{{ toYaml .Values.nsqd.resources | indent 10 }}
        command:
          - sh
        args:
          - -c
          - |
            /nsqd -data-path /data  \
            {{- range $i, $v := until (int .Values.lookupd.replicas) }}
            -lookupd-tcp-address nsq-lookupd-{{$i}}.nsq-lookupd:4161:4160 \
            {{- end }}
            -mem-queue-size "50" \
            -broadcast-address $HOSTNAME.nsqd
        ports:
        - name: tcp
          containerPort: 4150
          hostPort: 4150
        - name: http
          containerPort: 4151
          hostPort: 4151
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
        - "ReadWriteOnce"
      storageClassName: hdd
      resources:
        requests:
          storage: 50M
