{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nsq.serviceAccountName" . }}
  labels:
    app: {{ template "nsqd.name" . }}
    chart: {{ template "chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end -}}
