---
apiVersion: v1
kind: Service
metadata:
  name: activator-default
  labels:
    service: activator-default
spec:
  ports:
  - port: 1200
    protocol: TCP
    name: http
    targetPort: 1200
  selector:
    service: activator-default
