---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: activator-default
  name: activator-default
spec:
  ports:
    - name: http
      port: 1200
      protocol: TCP
      targetPort: http
  selector:
    service: activator-default
