---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: card
  name: card
spec:
  replicas: 1
  selector:
    matchLabels:
      service: card
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: card
    spec:
      containers:
        - command:
            - python
            - services/card/service.py
          envFrom:
            - configMapRef:
                name: noc-configmap
            - secretRef:
                name: noc-secret
          image: 'registry.getnoc.com/noc/noc/code:19.2-dev'
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          name: card
          ports:
            - containerPort: 1200
              name: http
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            limits:
              cpu: 500m
              memory: 150Mi
            requests:
              cpu: 50m
              memory: 150Mi
      priorityClassName: noc-card
      securityContext:
        runAsUser: 1200
      serviceAccountName: noc-service-account
      terminationGracePeriodSeconds: 30
