apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    service: card
  name: card
spec:
  replicas: 1
  selector:
    matchLabels:
      service: card
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: card
    spec:
      containers:
      - command:
        - python
        - services/card/service.py
        envFrom:
          - configMapRef:
              name: noc-configmap
          - secretRef:
              name: noc-secret
        image: registry.getnoc.com/noc/nocmc/release-19.1:master
        name: card
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
