---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: chwriter
  name: chwriter
spec:
  replicas: 1
  selector:
    matchLabels:
      service: chwriter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: chwriter
    spec:
      containers:
        - command:
            - python
            - services/chwriter/service.py
          envFrom:
            - configMapRef:
                name: noc-configmap
            - secretRef:
                name: noc-secret
          image: 'registry.getnoc.com/noc/noc/code:19.2-dev'
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          name: chwriter
          ports:
            - containerPort: 1200
              name: http
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            limits:
              cpu: 250m
              memory: 90Mi
            requests:
              cpu: 50m
              memory: 90Mi
      priorityClassName: noc-chwriter
      securityContext:
        runAsUser: 1200
      terminationGracePeriodSeconds: 30
