---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: classifier
  name: classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      service: classifier
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: classifier
    spec:
      containers:
        - command:
            - python
            - services/classifier/service.py
          env:
            - name: NOC_POOL
              value: default
          envFrom:
            - configMapRef:
                name: noc-configmap
            - secretRef:
                name: noc-secret
          image: 'registry.getnoc.com/noc/noc/code:19.2-dev'
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          name: classifier
          ports:
            - containerPort: 1200
              name: http
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            limits:
              cpu: 1
              memory: 120Mi
            requests:
              cpu: 50m
              memory: 120Mi
      priorityClassName: noc-classifier
      securityContext:
        runAsUser: 1200
      terminationGracePeriodSeconds: 30
