kind: Job
apiVersion: batch/v1
metadata:
  name: collection-init
spec:
  template:
    spec:
      containers:
      - name: collection-install
        image: registry.getnoc.com/noc/nocmc/stable:dev
        command:
          - /bin/sh
          - -c
        args:
          - python ./scripts/deploy/install-packages requirements/collections.json && ./noc collection sync
        envFrom:
          - configMapRef:
              name: noc-configmap
          - secretRef:
              name: noc-secret
      restartPolicy: Never
  backoffLimit: 1
