---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    service: correlator
  name: correlator
spec:
  replicas: 1
  selector:
    matchLabels:
      service: correlator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        service: correlator
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - command:
        - python
        - services/correlator/service.py
        envFrom:
          - configMapRef:
              name: noc-configmap
          - secretRef:
              name: noc-secret
        env:
            - name: NOC_POOL
              value: default
        image: registry.getnoc.com/noc/noc/code:19.2-dev
        imagePullPolicy: Always
        name: correlator
        livenessProbe:
          httpGet:
            path: /mon/
            port: 1200
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /mon/
            port: 1200
        resources:
          limits:
            cpu: 1
            memory: 120Mi
          requests:
            cpu: 50m
            memory: 120Mi
