---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    service: datastream
  name: datastream
spec:
  replicas: 1
  selector:
    matchLabels:
      service: datastream
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        service: datastream
    spec:
      securityContext:
        runAsUser: 1200
      terminationGracePeriodSeconds: 30
      containers:
        - command:
            - python
            - services/datastream/service.py
          envFrom:
            - configMapRef:
                name: noc-configmap
            - secretRef:
                name: noc-secret
          image: registry.getnoc.com/noc/noc/code:19.2-dev
          imagePullPolicy: Always
          name: datastream
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            limits:
              cpu: 500m
              memory: 110Mi
            requests:
              cpu: 50m
              memory: 110Mi
