kind: Job
apiVersion: batch/v1
metadata:
  name: db-init-migrate
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: registry.getnoc.com/noc/nocmc/release-19.1:master
        command:
          - ./noc
          - migrate
        envFrom:
          - configMapRef:
              name: noc-configmap
          - secretRef:
              name: noc-secret
      restartPolicy: Never
  backoffLimit: 1
