---
apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    service: discovery
spec:
  ports:
    - name: http
      port: 1200
      protocol: TCP
      targetPort: http
  selector:
    service: discovery
