---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: front-nginx
  name: front-nginx
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    service: front-nginx
