---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: front-nginx-ingress
spec:
  rules:
    - host: noc-k8s.getnoc.com
      http:
        paths:
          - backend:
              serviceName: front-nginx
              servicePort: 80
            path: /
  tls:
    - hosts:
        - noc-k8s.getnoc.com
      secretName: tls-secret
