---
apiVersion: v1
kind: Service
metadata:
  name: front-nginx
  labels:
    service: front-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: 80
  selector:
    service: front-nginx
