apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    service: grafanads
  name: grafanads
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grafanads
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        service: grafanads
    spec:
      containers:
      - command:
        - python
        - services/grafanads/service.py
        envFrom:
          - configMapRef:
              name: noc-configmap
          - secretRef:
              name: noc-secret
        image: registry.getnoc.com/noc/noc/code:19.2-dev
        imagePullPolicy: Always
        name: grafanads
        livenessProbe:
          httpGet:
            path: /mon/
            port: 1200
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /mon/
            port: 1200
        resources:
          limits:
            #cpu: 100m
            memory: 110Mi
          requests:
            #cpu: 100m
            memory: 110Mi
