---
kind: Job
apiVersion: batch/v1
metadata:
  name: init
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: registry.getnoc.com/noc/noc/dev:19.2-dev
          command:
            - "sh"
            - "-c"
            - >
              set -xe
              && /usr/bin/python ./commands/migrate.py
              && ./noc ensure-indexes
              && /usr/bin/python ./commands/migrate-ch.py
              && /usr/bin/python ./scripts/deploy/install-packages
                requirements/collections.json
              && ./noc collection sync
              && ./noc sync-perm
              && ./noc sync-mibs
              && mkdir -p /opt/noc/etc
              && echo
                'cG9vbHM6CiAgZGVmYXVsdDoKICAgIGRlc2NyaXB0aW9uOiBkZWZhdWx0Cg=='
                |base64 -d > /opt/noc/etc/noc.yml
              && cat /opt/noc/etc/noc.yml
              && /usr/bin/python ./scripts/deploy/apply-pools
          envFrom:
            - configMapRef:
                name: noc-configmap
            - secretRef:
                name: noc-secret
          resources:
            limits:
              cpu: 1
              memory: 250Mi
            requests:
              cpu: 1
              memory: 250Mi
