---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: login
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      service: login
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: login
    spec:
      containers:
        - command:
            - python
            - services/login/service.py
          envFrom:
            - configMapRef:
                name: noc-configmap
            - secretRef:
                name: noc-secret
          image: 'registry.getnoc.com/noc/noc/code:19.2-dev'
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          name: login
          ports:
            - containerPort: 1200
              name: http
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            limits:
              cpu: 250m
              memory: 75Mi
            requests:
              cpu: 50m
              memory: 75Mi
          securityContext:
            runAsUser: 1200
      priorityClassName: noc-login
      serviceAccountName: noc-service-account
      terminationGracePeriodSeconds: 30
