---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    service: login
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      service: login
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        service: login
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - command:
            - python
            - services/login/service.py
          envFrom:
            - configMapRef:
                name: noc-configmap
            - secretRef:
                name: noc-secret
          image: registry.getnoc.com/noc/noc/code:19.2-dev
          imagePullPolicy: Always
          name: login
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            limits:
              cpu: 250m
              memory: 75Mi
            requests:
              cpu: 50m
              memory: 75Mi
