---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    service: mailsender
  name: mailsender
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mailsender
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        service: mailsender
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - command:
        - python
        - services/mailsender/service.py
        envFrom:
          - configMapRef:
              name: noc-configmap
          - secretRef:
              name: noc-secret
        image: registry.getnoc.com/noc/noc/code:19.2-dev
        imagePullPolicy: Always
        name: mailsender
        livenessProbe:
          httpGet:
            path: /mon/
            port: 1200
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /mon/
            port: 1200
        resources:
          limits:
            cpu: 100m
            memory: 52Mi
          requests:
            cpu: 50m
            memory: 52Mi
