---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mib
  name: mib
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mib
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: mib
    spec:
      containers:
        - command:
            - python
            - services/mib/service.py
          envFrom:
            - configMapRef:
                name: noc-configmap
            - secretRef:
                name: noc-secret
          image: 'registry.getnoc.com/noc/noc/code:19.2-dev'
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          name: mib
          ports:
            - containerPort: 1200
              name: http
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
      priorityClassName: noc-mib
      securityContext:
        runAsUser: 1200
      terminationGracePeriodSeconds: 30
