apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    service: nbi
  name: nbi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nbi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        service: nbi
    spec:
      containers:
      - command:
        - python
        - services/nbi/service.py
        envFrom:
          - configMapRef:
              name: noc-configmap
          - secretRef:
              name: noc-secret
        image: registry.getnoc.com/noc/noc/code:19.2-dev
        imagePullPolicy: Always
        name: nbi
        livenessProbe:
          httpGet:
            path: /mon/
            port: 1200
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /mon/
            port: 1200
        resources:
          limits:
            cpu: 250m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
