---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: ping
  name: ping
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ping
  serviceName: ping
  template:
    metadata:
      labels:
        service: ping
    spec:
      containers:
        - command:
            - python
            - services/ping/service.py
          env:
            - name: NOC_POOL
              value: default
          envFrom:
            - configMapRef:
                name: noc-configmap
            - secretRef:
                name: noc-secret
          image: 'registry.getnoc.com/noc/noc/code:19.2-dev'
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          name: ping
          ports:
            - containerPort: 1200
              name: http
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi
          #  @todo investigate how to set NET_RAW for python script
          # securityContext:
          #   capabilities:
          #     add:
          #       - NET_RAW
      priorityClassName: noc-ping
      #  @todo investigate how to set NET_RAW for python script
      # securityContext:
      #   runAsUser: 1200
      serviceAccountName: noc-service-account
      terminationGracePeriodSeconds: 30
