dependencies:
  - name: consul
    version: 0.8.1
    repository: "file://charts/consul"
  - name: clickhouse
    version: 0.1.0
    repository: "file://charts/clickhouse"
  - name: nsqd
    version: 0.1.0
    repository: "file://charts/nsqd"
  - name: mongodb
    version: 6.1.5
    repository: "@stable"
  - name: postgresql
    version: 0.15.0
    repository: "@stable"
  - name: grafana
    version: 3.5.12
    repository: "@stable"
