---
apiVersion: v1
kind: Service
metadata:
  name: selfmon
  labels:
    service: selfmon
spec:
  ports:
    - name: http
      port: 1200
      protocol: TCP
      targetPort: http
  selector:
    service: selfmon
