---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: nginx
    spec:
      containers:
        - command: null
          image: 'registry.getnoc.com/noc/noc/static:19.2-dev'
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /ng_stats
              port: 81
            initialDelaySeconds: 10
          name: nginx
          readinessProbe:
            httpGet:
              path: /ng_stats
              port: 81
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: 10m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
          volumeMounts:
            - mountPath: /etc/nginx
              name: nginx-configmap
              readOnly: true
      priorityClassName: noc-nginx
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: noc.conf
                path: conf.d/noc.conf
              - key: hc.conf
                path: conf.d/hc.conf
              - key: mime.types
                path: mime.types
            name: nginx-configmap
          name: nginx-configmap
      serviceAccountName: noc-service-account
