---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: static-ingress
spec:
  rules:
    - host: noc-k8s.getnoc.com
      http:
        paths:
          - backend:
              serviceName: nginx-service
              servicePort: 80
            path: /media
          - backend:
              serviceName: nginx-service
              servicePort: 80
            path: /ui
  tls:
    - hosts:
        - noc-k8s.getnoc.com
      secretName: tls-secret
