---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: tgsender
  name: tgsender
spec:
  replicas: 1
  selector:
    matchLabels:
      service: tgsender
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: tgsender
    spec:
      containers:
        - command:
            - python
            - services/tgsender/service.py
          envFrom:
            - configMapRef:
                name: noc-configmap
            - secretRef:
                name: noc-secret
          image: 'registry.getnoc.com/noc/noc/code:19.2-dev'
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          name: tgsender
          ports:
            - containerPort: 1200
              name: http
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            limits:
              cpu: 100m
              memory: 52Mi
            requests:
              cpu: 100m
              memory: 52Mi
          securityContext:
            runAsUser: 1200
      priorityClassName: noc-tgsender
      serviceAccountName: noc-service-account
      terminationGracePeriodSeconds: 30
