---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: trapcollector
  name: trapcollector
spec:
  replicas: 0
  selector:
    matchLabels:
      service: trapcollector
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: trapcollector
    spec:
      containers:
        - command:
            - python
            - services/trapcollector/service.py
          env:
            - name: NOC_POOL
              value: default
          envFrom:
            - configMapRef:
                name: noc-configmap
            - secretRef:
                name: noc-secret
          image: 'registry.getnoc.com/noc/noc/code:19.2-dev'
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          name: trapcollector
          ports:
            - containerPort: 1200
              name: http
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            limits:
              cpu: 200m
              memory: 80Mi
            requests:
              cpu: 50m
              memory: 80Mi
          securityContext:
            runAsUser: 1200
      priorityClassName: noc-trapcollector
      serviceAccountName: noc-service-account
      terminationGracePeriodSeconds: 30
