---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: trapcollector
  name: trapcollector
spec:
  ports:
    - name: http
      port: 1200
      protocol: TCP
      targetPort: http
  selector:
    service: trapcollector
