---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    service: trapcollector
  name: trapcollector
spec:
  replicas: 1
  selector:
    matchLabels:
      service: trapcollector
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        service: trapcollector
    spec:
      securityContext:
        runAsUser: 1200
      terminationGracePeriodSeconds: 30
      priorityClassName: noc-trapcollector
      containers:
        - command:
            - python
            - services/trapcollector/service.py
          envFrom:
            - configMapRef:
                name: noc-configmap
            - secretRef:
                name: noc-secret
          env:
            - name: NOC_POOL
              value: default
          image: registry.getnoc.com/noc/noc/code:19.2-dev
          imagePullPolicy: Always
          name: trapcollector
          ports:
            - containerPort: 1200
              name: http
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            limits:
              cpu: 200m
              memory: 80Mi
            requests:
              cpu: 50m
              memory: 80Mi
