---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "noc.datastream.fullname" . }}
  labels:
    service: datastream
{{ include "noc.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.service_config.global.datastream.count }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "noc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      service: datastream
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "noc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        service: datastream
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - command:
            - python
            - services/datastream/service.py
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-noc-configmap
            - secretRef:
                name: {{ .Release.Name }}-noc-secret
          image: "{{ .Values.image.repository }}/code:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          name: datastream
          ports:
            - containerPort: 1200
              name: http
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            {{- toYaml .Values.resources.datastream | nindent 12 }}
          securityContext:
            runAsUser: 1200
      priorityClassName: noc-datastream
      serviceAccountName: noc-service-account
      terminationGracePeriodSeconds: 30
      {{- with .Values.service_config.global.datastream.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.service_config.global.datastream.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations.datastream }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
