---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "noc.datasource.fullname" . }}
  labels:
    service: datasource
{{ include "noc.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount.global.datasource }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "noc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      service: datasource
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "noc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        service: datasource
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - command:
            - python
            - services/datasource/service.py
          envFrom:
            - configMapRef:
                name: noc-configmap
            - secretRef:
                name: noc-secret
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          name: datasource
          ports:
            - containerPort: 1200
              name: http
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            {{- toYaml .Values.resources.datasource | nindent 12 }}
          securityContext:
            runAsUser: 1200
      priorityClassName: noc-datasource
      serviceAccountName: noc-service-account
      terminationGracePeriodSeconds: 30
      {{- with .Values.nodeSelector.datasource }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity.datasource }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations.datasource }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
