---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "noc.discovery.fullname" . }}
  labels:
    service: discovery
    pool: default
{{ include "noc.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount.pools.default.discovery }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "noc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      service: discovery
      pool: default
  serviceName: discovery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "noc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        service: discovery
        pool: default
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - command:
            - python
            - services/discovery/service.py
          env:
            - name: NOC_POOL
              value: default
          envFrom:
            - configMapRef:
                name: noc-configmap
            - secretRef:
                name: noc-secret
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          name: discovery
          ports:
            - containerPort: 1200
              name: http
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            {{- toYaml .Values.resources.discovery | nindent 12 }}
          securityContext:
            runAsUser: 1200
      priorityClassName: noc-discovery
      serviceAccountName: noc-service-account
      terminationGracePeriodSeconds: 30
      {{- with .Values.nodeSelector.discovery }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity.discovery }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations.discovery }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

