---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "noc.front.fullname" . }}
  labels:
    service: front-nginx
{{ include "noc.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount.global.front }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "noc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      service: front-nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "noc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        service: front-nginx
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - command: null
          image: 'nginx:mainline-alpine'
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /ng_stats
              port: 81
            initialDelaySeconds: 10
          name: front-nginx
          readinessProbe:
            httpGet:
              path: /ng_stats
              port: 81
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources.front | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/nginx
              name: front-nginx-configmap
              readOnly: true
      priorityClassName: noc-nginx
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: noc.conf
                path: conf.d/noc.conf
              - key: upstream.conf
                path: upstream.conf
              - key: hc.conf
                path: conf.d/hc.conf
              - key: mime.types
                path: mime.types
            name: front-nginx-configmap
          name: front-nginx-configmap
      serviceAccountName: noc-service-account
      {{- with .Values.nodeSelector.front }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity.front }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations.front }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
