---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "noc.ping.fullname" . }}
  labels:
    service: ping
    pool: default
{{ include "noc.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount.pools.default.ping }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "noc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      service: discovery
      pool: default
  serviceName: discovery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "noc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        service: discovery
        pool: default
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - command:
            - python
            - services/ping/service.py
          env:
            - name: NOC_POOL
              value: default
          envFrom:
            - configMapRef:
                name: noc-configmap
            - secretRef:
                name: noc-secret
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          name: ping
          ports:
            - containerPort: 1200
              name: http
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            {{- toYaml .Values.resources.ping | nindent 12 }}
          #  @todo investigate how to set NET_RAW for python script
          # securityContext:
          #   capabilities:
          #     add:
          #       - NET_RAW
      priorityClassName: noc-ping
      #  @todo investigate how to set NET_RAW for python script
      # securityContext:
      #   runAsUser: 1200
      serviceAccountName: noc-service-account
      terminationGracePeriodSeconds: 30
      {{- with .Values.nodeSelector.ping }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity.ping }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations.ping }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
