---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "noc.selfmon.fullname" . }}
  labels:
    service: selfmon
{{ include "noc.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.service_config.global.selfmon.count }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "noc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      service: selfmon
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "noc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        service: selfmon
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - command:
            - python
            - services/selfmon/service.py
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-noc-configmap
            - secretRef:
                name: {{ .Release.Name }}-noc-secret
          image: "{{ .Values.image.repository }}/code:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          name: selfmon
          ports:
            - containerPort: 1200
              name: http
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            {{- toYaml .Values.resources.selfmon | nindent 12 }}
          securityContext:
            runAsUser: 1200
    {{- if .Values.priorityClass.create }}
      priorityClassName: noc-selfmon
    {{- end }}
    {{- if .Values.rbac.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
    {{- end}}
      terminationGracePeriodSeconds: 30
      {{- with .Values.service_config.global.selfmon.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.service_config.global.selfmon.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations.selfmon }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
