---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "noc.syslogcollector.fullname" . }}
  labels:
    service: syslogcollector
    pool: default
{{ include "noc.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount.pools.default.syslogcollector }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "noc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      service: syslogcollector
      pool: default
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "noc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        service: syslogcollector
        pool: default
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - command:
            - python
            - services/syslogcollector/service.py
          env:
            - name: NOC_POOL
              value: default
          envFrom:
            - configMapRef:
                name: noc-configmap
            - secretRef:
                name: noc-secret
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          name: syslogcollector
          ports:
            - containerPort: 1200
              name: http
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            {{- toYaml .Values.resources.syslogcollector | nindent 12 }}
          securityContext:
            runAsUser: 1200
      priorityClassName: noc-syslogcollector
      serviceAccountName: noc-service-account
      terminationGracePeriodSeconds: 30
      {{- with .Values.nodeSelector.syslogcollector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity.syslogcollector }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations.syslogcollector }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
