---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nsq-admin
  name: nsq-admin
spec:
  ports:
    - name: http
      port: 4171
      protocol: TCP
      targetPort: 4171
  selector:
    app: nsq-admin
