---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nsq-admin
  name: nsq-admin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nsq-admin
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: component
                      operator: In
                      values:
                        - nsqadmin
                    - key: app
                      operator: In
                      values:
                        - nsq
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - command:
            - /nsqadmin
            - '-lookupd-http-address'
            - 'nsq-lookupd-0.nsq-lookupd:4161'
          image: 'docker.io/nsqio/nsq:v1.1.0'
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
          name: nsq-admin
          ports:
            - containerPort: 4171
              name: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
