# Source: nsq/templates/
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nsq-admin
  labels:
    app: nsq-admin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nsq-admin
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: component
                    operator: In
                    values:
                      - nsqadmin
                  - key: app
                    operator: In
                    values:
                      - nsq
              topologyKey: kubernetes.io/hostname
      containers:
      - name: nsq-admin
        image: docker.io/nsqio/nsq:v1.1.0
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
        command:
          - /nsqadmin
          - -lookupd-http-address
          - nsq-lookupd-0.nsq-lookupd:4161
        ports:
        - name: http
          containerPort: 4171
