---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nsq-lookupd
  name: nsq-lookupd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsq-lookupd
      component: nsqlookupd
  serviceName: nsq-lookupd
  template:
    metadata:
      labels:
        app: nsq-lookupd
        component: nsqlookupd
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: component
                      operator: In
                      values:
                        - nsqlookupd
                    - key: app
                      operator: In
                      values:
                        - nsq
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - command:
            - /nsqlookupd
          image: 'docker.io/nsqio/nsq:v1.1.0'
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
          name: nsqlookupd
          ports:
            - containerPort: 4160
              name: tcp
            - containerPort: 4161
              name: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 2
          resources:
            limits:
              cpu: 150m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
      terminationGracePeriodSeconds: 5
