---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nsq-lookupd
  name: nsq-lookupd
spec:
  clusterIP: None
  ports:
    - name: tcp
      port: 4160
      protocol: TCP
      targetPort: 4160
    - name: http
      port: 4161
      protocol: TCP
      targetPort: 4161
  selector:
    app: nsq-lookupd
