---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nsq-lookupd
  labels:
    app: nsq-lookupd
spec:
  selector:
    matchLabels:
      app: nsq-lookupd
      component: nsqlookupd
  serviceName: "nsq-lookupd"
  replicas: 1
  template:
    metadata:
      labels:
        app: nsq-lookupd
        component: nsqlookupd
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                      - nsqlookupd
                  - key: app
                    operator: In
                    values:
                      - nsq
                topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 5
      containers:
      - name: nsqlookupd
        image: docker.io/nsqio/nsq:v1.0.0-compat
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
        command:
        - /nsqlookupd
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 2
        ports:
        - name: tcp
          containerPort: 4160
        - name: http
          containerPort: 4161
