# Source: nsq/templates/lookupd-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nsq-lookupd
  labels:
    app: nsq-lookupd
spec:
  clusterIP: None
  ports:
  - port: 4160
    protocol: TCP
    name: tcp
    targetPort: 4160
  - port: 4161
    protocol: TCP
    name: http
    targetPort: 4161
  selector:
    app: nsq-lookupd
