# Source: nsq/templates/nsqd-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nsqd
  labels:
    app: nsqd
spec:
  ports:
  - port: 4150
    protocol: TCP
    name: tcp
    targetPort: 4150
  - port: 4151
    protocol: TCP
    name: http
    targetPort: 4151
  selector:
    app: nsq-nsqd
