---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nsq-nsqd
  name: nsq-nsqd
spec:
  selector:
    matchLabels:
      app: nsq-nsqd
      component: nsqd
  serviceName: nsqd
  template:
    metadata:
      labels:
        app: nsq-nsqd
        component: nsqd
    spec:
      containers:
        - args:
            - '-c'
            - |
              /nsqd -data-path /data  \
              -lookupd-tcp-address nsq-lookupd-0.nsq-lookupd:4160 \
              -mem-queue-size "10000" \
              -broadcast-address ${HOSTNAME}.nsqd
          command:
            - sh
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          image: 'docker.io/nsqio/nsq:v1.1.0'
          name: nsqd
          ports:
            - containerPort: 4150
              hostPort: 4150
              name: tcp
            - containerPort: 4151
              hostPort: 4151
              name: http
          resources:
            limits:
              cpu: 500m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
          volumeMounts:
            - mountPath: /data
              name: datadir
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 64Mi
