---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: nsq-nsqd
  name: nsq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nsq
subjects:
  - kind: ServiceAccount
    name: nsq
