---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: nsq
  labels:
    app: nsq-nsqd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nsq
subjects:
- kind: ServiceAccount
  name: nsq
