---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: activator-servicemonitor
  labels:
    service: activator
spec:
  selector:
    matchLabels:
      service: activator
  endpoints:
    - port: http
