---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bi-servicemonitor
  labels:
    service: bi
spec:
  selector:
    matchLabels:
      service: bi
  endpoints:
    - port: http
