---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: card-servicemonitor
  labels:
    service: card
spec:
  selector:
    matchLabels:
      service: card
  endpoints:
    - port: http
