---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: correlator-servicemonitor
  labels:
    service: correlator
spec:
  selector:
    matchLabels:
      service: correlator
  endpoints:
    - port: http
