---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: datastream-servicemonitor
  labels:
    service: datastream
spec:
  selector:
    matchLabels:
      service: datastream
  endpoints:
    - port: http
