---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: datasource-servicemonitor
  labels:
    service: datasource
spec:
  selector:
    matchLabels:
      service: datasource
  endpoints:
    - port: http
