---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: discovery-servicemonitor
  labels:
    service: discovery
spec:
  selector:
    matchLabels:
      service: discovery
  endpoints:
    - port: http
