---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: escalator-servicemonitor
  labels:
    service: escalator
spec:
  selector:
    matchLabels:
      service: escalator
  endpoints:
    - port: http
