---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafanads-servicemonitor
  labels:
    service: grafanads
spec:
  selector:
    matchLabels:
      service: grafanads
  endpoints:
    - port: http
