---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: login-servicemonitor
  labels:
    service: login
spec:
  selector:
    matchLabels:
      service: login
  endpoints:
    - port: http
