---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mrt-servicemonitor
  labels:
    service: mrt
spec:
  selector:
    matchLabels:
      service: mrt
  endpoints:
    - port: http
