---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nbi-servicemonitor
  labels:
    service: nbi
spec:
  selector:
    matchLabels:
      service: nbi
  endpoints:
    - port: http
