---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ping-servicemonitor
  labels:
    service: ping
spec:
  selector:
    matchLabels:
      service: ping
  endpoints:
    - port: http
