---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sae-servicemonitor
  labels:
    service: sae
spec:
  selector:
    matchLabels:
      service: sae
  endpoints:
    - port: http
