---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scheduler-servicemonitor
  labels:
    service: scheduler
spec:
  selector:
    matchLabels:
      service: scheduler
  endpoints:
    - port: http
