---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: syslogcollector-servicemonitor
  labels:
    service: syslogcollector
spec:
  selector:
    matchLabels:
      service: syslogcollector
  endpoints:
    - port: http
