---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trapcollector-servicemonitor
  labels:
    service: trapcollector
spec:
  selector:
    matchLabels:
      service: trapcollector
  endpoints:
    - port: http
