---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-servicemonitor
  labels:
    service: web
spec:
  selector:
    matchLabels:
      service: web
  endpoints:
    - port: http
