---
# Source: nsq/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nsq
  labels:
    app: nsq-nsqd
    chart: nsq-v0.1.0
    release: "nsq"
    heritage: "Tiller"
---
# Source: nsq/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: nsq
  labels:
    app: nsq-nsqd
    chart: nsq-v0.1.0
    release: "nsq"
    heritage: "Tiller"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nsq
subjects:
- kind: ServiceAccount
  name: nsq
---
# Source: nsq/templates/admin-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nsq-admin
  labels:
    app: nsq-admin
    chart: nsq-v0.1.0
    release: nsq
    heritage: Tiller
spec:
  ports:
  - port: 4171
    protocol: TCP
    name: http
    targetPort: 4171
  selector:
    app: nsq-admin

---
# Source: nsq/templates/lookupd-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nsq-lookupd
  labels:
    app: nsq-lookupd
    chart: nsq-v0.1.0
    release: nsq
    heritage: Tiller
spec:
  clusterIP: None
  ports:
  - port: 4160
    protocol: TCP
    name: tcp
    targetPort: 4160
  - port: 4161
    protocol: TCP
    name: http
    targetPort: 4161
  selector:
    app: nsq-lookupd

---
# Source: nsq/templates/admin-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nsq-admin
  labels:
    app: nsq-admin
    chart: nsq-v0.1.0
    release: nsq
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nsq-admin
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: component
                    operator: In
                    values:
                      - nsqadmin
                  - key: app
                    operator: In
                    values:
                      - nsq
              topologyKey: kubernetes.io/hostname
      containers:
      - name: nsq-admin
        image: docker.io/nsqio/nsq:v1.0.0-compat
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
          
        command:
          - /nsqadmin
          - -lookupd-http-address
          - nsq-lookupd-0.nsq-lookupd:4161
        ports:
        - name: http
          containerPort: 4171

---
# Source: nsq/templates/lookupd-sts.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nsq-lookupd
  labels:
    app: nsq-lookupd
    chart: nsq-v0.1.0
    release: nsq
    heritage: Tiller
spec:
  selector:
    matchLabels:
      app: nsq-lookupd
      component: nsqlookupd
  serviceName: "nsqlookupd"
  replicas: 1
  template:
    metadata:
      labels:
        app: nsq-lookupd
        component: nsqlookupd
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                      - nsqlookupd
                  - key: app
                    operator: In
                    values:
                      - nsq
                topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 5
      containers:
      - name: nsqlookupd
        image: docker.io/nsqio/nsq:v1.0.0-compat
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
          
        command:
        - /nsqlookupd
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 2
        ports:
        - name: tcp
          containerPort: 4160
        - name: http
          containerPort: 4161

---
# Source: nsq/templates/nsqd-sts.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nsq-nsqd
  labels:
    app: nsq-nsqd
    chart: nsq-v0.1.0
    release: nsq
    heritage: Tiller
spec:
  selector:
    matchLabels:
      app: nsq-nsqd
      component: nsqd
  serviceName: "nsqd"
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nsq-nsqd
        component: nsqd
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9117'
    spec:
      containers:
      - name: nsqd
        image: docker.io/nsqio/nsq:v1.0.0-compat
        volumeMounts:
        - name: datadir
          mountPath: /data
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
          
        command:
          - sh
        args:
          - -c
          - |
            /nsqd -data-path /data  \
            -lookupd-tcp-address nsq-lookupd-0.nsq-lookupd:4161:4160 \
            -mem-queue-size "50" \
            -broadcast-address $HOSTNAME.nsqd
        ports:
        - name: tcp
          containerPort: 4150
          hostPort: 4150
        - name: http
          containerPort: 4151
          hostPort: 4151
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
        - "ReadWriteOnce"
      storageClassName: hdd
      resources:
        requests:
          storage: 50M

---
# Source: nsq/templates/role.yaml

