apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: clickhouse-server
  namespace: default
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: clickhouse
    spec:
      initContainers:
      - name: config
        image: alpine:3.6
        command:
          - '/bin/sh'
          - '-c'
          - cd /etc/clickhouse-server;
            ln -sf /etc/clickhouse-server-config/config.xml;
            ln -sf /etc/clickhouse-server-config/users.xml;
            chown 105:106 /var/lib/clickhouse/
        volumeMounts:
          - mountPath: /var/lib/clickhouse/
            name: ch-datadir
          - mountPath: /etc/clickhouse-server/
            name: config-directory
          - mountPath: /etc/clickhouse-server-config/
            name: config-volume
      containers:
      - name: clickhouse
        image: yandex/clickhouse-server:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8123
        - name: native
          containerPort: 9000
        env:
        - name: CLICKHOUSE_SERVER
          value: "clickhouse"
        - name: CLICKHOUSE_PORT
          value: "9000"
        - name: CLICKHOUSE_USER
          value: "default"
        - name: CLICKHOUSE_PASS
          value: "noc"
        - name: CLICKHOUSE_DB
          value: "logs"
        - name: K8S_LOGS_TABLE
          value: "logs"
        livenessProbe:
          timeoutSeconds: 1
          initialDelaySeconds: 30
          tcpSocket:
            port: 9000
        readinessProbe:
          timeoutSeconds: 1
          initialDelaySeconds: 5
          tcpSocket:
            port: 9000
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 2
            memory: 11Gi
        volumeMounts:
          - mountPath: /var/lib/clickhouse/
            name: ch-datadir
          - mountPath: /etc/clickhouse-server/
            name: config-directory
          - mountPath: /etc/clickhouse-server-config/
            name: config-volume
      volumes:
        - name: ch-datadir
          persistentVolumeClaim:
            claimName: ch-datadir
        - name: config-volume
          configMap:
            name: clickhouse-config
        - name: config-directory
          emptyDir:
            sizeLimit: "0"

