{{- $root := . }}
{{- range $pool, $pool_info:= .Values.service_config.pools }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ printf "%s-discovery-%s" $root.Release.Name $pool | trunc 63 | trimSuffix "-" }}
  labels:
    service: discovery
    pool: {{ $pool }}
{{ include "noc.labels" $root | indent 4 }}
spec:
  replicas: {{ $pool_info.discovery.count }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "noc.name" $root }}
      app.kubernetes.io/instance: {{ $root.Release.Name }}
      service: discovery
      pool: {{ $pool }}
  serviceName: discovery-{{ $pool }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "noc.name" $root }}
        app.kubernetes.io/instance: {{ $root.Release.Name }}
        service: discovery
        pool: {{ $pool }}
    spec:
    {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - command:
            - python
            - services/discovery/service.py
          env:
            - name: NOC_POOL
              value: {{ $pool }}
          envFrom:
            - configMapRef:
                name: noc-configmap
            - secretRef:
                name: noc-secret
          image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          name: discovery-{{ $pool }}
          ports:
            - containerPort: 1200
              name: http
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            {{- toYaml $root.Values.resources.discovery | nindent 12 }}
          securityContext:
            runAsUser: 1200
      priorityClassName: noc-discovery
      serviceAccountName: noc-service-account
      terminationGracePeriodSeconds: 30
      {{- with $pool_info.discovery.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $pool_info.discovery.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $root.Values.tolerations.discovery }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
