{{- $root := . }}
{{- range $pool, $pool_info:= .Values.service_config.pools }}
{{- if index $pool_info "ping" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ printf "%s-ping-%s" $root.Release.Name $pool | trunc 63 | trimSuffix "-" }}
  labels:
    service: ping
    pool: {{ $pool }}
{{ include "noc.labels" $root | indent 4 }}
spec:
  replicas: {{ $pool_info.ping.count }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "noc.name" $root }}
      app.kubernetes.io/instance: {{ $root.Release.Name }}
      service: ping
      pool: {{ $pool }}
  serviceName: ping-{{ $pool }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "noc.name" $root }}
        app.kubernetes.io/instance: {{ $root.Release.Name }}
        service: ping
        pool: {{ $pool }}
    spec:
    {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $root.Values.nocInitContainer }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
      containers:
        - command:
            - python
            - services/ping/service.py
          env:
            - name: NOC_POOL
              value: {{ $pool }}
          envFrom:
            - configMapRef:
                name: {{ $root.Release.Name }}-noc-configmap
            - secretRef:
                name: {{ $root.Release.Name }}-noc-secret
          image: "{{ $root.Values.image.repository }}/code:{{ $root.Values.image.tag }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          name: ping-{{ $pool }}
          ports:
            - containerPort: 1200
              name: http
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            {{- toYaml $root.Values.resources.ping | nindent 12 }}
          #  @todo investigate how to set NET_RAW for python script
          # securityContext:
          #   capabilities:
          #     add:
          #       - NET_RAW
    {{- if $root.Values.priorityClass.create }}
      priorityClassName: noc-ping
    {{- end }}
      #  @todo investigate how to set NET_RAW for python script
      # securityContext:
      #   runAsUser: 1200
    {{- if $root.Values.rbac.create }}
      serviceAccountName: {{ $root.Values.serviceAccount.name }}
    {{- end}}
      terminationGracePeriodSeconds: 30
      {{- with $pool_info.ping.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $pool_info.ping.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $root.Values.tolerations.ping }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
{{- end }}
