{{- $root := . }}
{{- range $pool, $pool_info:= .Values.service_config.pools }}
{{- if index $pool_info "trapcollector" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-trapcollector-%s" $root.Release.Name $pool | trunc 63 | trimSuffix "-" }}
  labels:
    service: trapcollector
    pool: {{ $pool }}
{{ include "noc.labels" $root | indent 4 }}
spec:
  replicas: {{ $pool_info.trapcollector.count }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "noc.name" $root }}
      app.kubernetes.io/instance: {{ $root.Release.Name }}
      service: trapcollector
      pool: {{ $pool }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "noc.name" $root }}
        app.kubernetes.io/instance: {{ $root.Release.Name }}
        service: trapcollector
        pool: {{ $pool }}
    spec:
    {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - command:
            - python
            - services/trapcollector/service.py
          env:
            - name: NOC_POOL
              value: {{ $pool }}
          envFrom:
            - configMapRef:
                name: {{ $root.Release.Name }}-noc-configmap
            - secretRef:
                name: {{ $root.Release.Name }}-noc-secret
          image: "{{ $root.Values.image.repository }}/code:{{ $root.Values.image.tag }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /mon/
              port: 1200
            initialDelaySeconds: 10
          name: trapcollector-{{ $pool }}
          ports:
            - containerPort: 1200
              name: http
          readinessProbe:
            httpGet:
              path: /mon/
              port: 1200
          resources:
            {{- toYaml $root.Values.resources.trapcollector | nindent 12 }}
          securityContext:
            runAsUser: 1200
      priorityClassName: noc-trapcollector
      serviceAccountName: noc-service-account
      terminationGracePeriodSeconds: 30
      {{- with $pool_info.trapcollector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $pool_info.trapcollector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $root.Values.tolerations.trapcollector }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
{{- end }}
