---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-ingress"
  labels:
{{ include "noc.labels" . | indent 4 }}
spec:
  tls:
    - hosts:
       - '{{ .Values.noc_web.address }}'
      secretName: '{{ .Values.noc_web.tls_secretName }}'
  rules:
    - host: '{{ .Values.noc_web.address }}'
      http:
        paths:
          - backend:
              serviceName: '{{ template "noc.static.fullname" $ }}'
              servicePort: http
            path: /media
          - backend:
              serviceName: '{{ template "noc.static.fullname" $ }}'
              servicePort: http
            path: /ui
          - backend:
              serviceName: '{{ template "noc.static.fullname" $ }}'
              servicePort: http
            path: /favicon.ico
          - backend:
              serviceName: '{{ template "noc.front.fullname" $ }}'
              servicePort: http
            path: /
          - backend:
              serviceName: '{{ template "noc.front.fullname" $ }}'
              servicePort: http
            path: /ui/grafana
