---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: noc-service-account
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: noc-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["noc-secret"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["noc-configmap"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: noc-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: noc-role
subjects:
  - kind: ServiceAccount
    name: noc-service-account
