---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-consul
value: 1200000
globalDefault: false
description: "This priority class for consul"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-postgres
value: 1000000
globalDefault: false
description: "This priority class for noc postgres"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-mongo
value: 1000005
globalDefault: false
description: "This priority class for noc mongodb"

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-activator
value: 1000005
globalDefault: false
description: "This priority class for noc activator"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-bi
value: 900000
globalDefault: false
description: "This priority class for noc bi"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-card
value: 1000005
globalDefault: false
description: "This priority class for noc card"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-chwriter
value: 1000005
globalDefault: false
description: "This priority class for noc chwriter"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-classifier
value: 1000005
globalDefault: false
description: "This priority class for noc classifier"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-correlator
value: 1000005
globalDefault: false
description: "This priority class for noc correlator"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-datasource
value: 1000005
globalDefault: false
description: "This priority class for noc datasource"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-datastream
value: 1000005
globalDefault: false
description: "This priority class for noc datastream"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-escalator
value: 1000005
globalDefault: false
description: "This priority class for noc escalator"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-grafanads
value: 1000005
globalDefault: false
description: "This priority class for noc grafanads"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-login
value: 1000005
globalDefault: false
description: "This priority class for noc login"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-mailsender
value: 1000005
globalDefault: false
description: "This priority class for noc mailsender"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-mib
value: 500000
globalDefault: false
description: "This priority class for noc mib"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-mrt
value: 1000005
globalDefault: false
description: "This priority class for noc mrt"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-nbi
value: 1000005
globalDefault: false
description: "This priority class for noc nbi"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-sae
value: 1000005
globalDefault: false
description: "This priority class for noc sae"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-scheduler
value: 1000005
globalDefault: false
description: "This priority class for noc scheduler"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-selfmon
value: 1000005
globalDefault: false
description: "This priority class for noc selfmon"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-syslogcollector
value: 1000005
globalDefault: false
description: "This priority class for noc syslogcollector"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-tgsender
value: 1000005
globalDefault: false
description: "This priority class for noc tgsender"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-trapcollector
value: 1000005
globalDefault: false
description: "This priority class for noc trapcollector"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-web
value: 1000005
globalDefault: false
description: "This priority class for noc web"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-discovery
value: 1000005
globalDefault: false
description: "This priority class for noc discovery"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-ping
value: 1000005
globalDefault: false
description: "This priority class for noc ping"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: noc-nginx
value: 1000005
globalDefault: false
description: "This priority class for noc nginx"
