---
apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    name: nginx-ingress-microk8s
  type: LoadBalancer
