---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsqd.lookupd.fullname" . }}
  labels:
    service: lookupd
{{ include "nsqd.labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
    - name: tcp
      port: 4160
      protocol: TCP
      targetPort: 4160
    - name: http
      port: 4161
      protocol: TCP
      targetPort: 4161
  selector:
    service: lookupd
    app.kubernetes.io/name: {{ include "nsqd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
