{{- $root := . }}
{{- range $pool, $pool_info:= .Values.service_config.pools }}
{{- if index $pool_info "trapcollector" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-trapcollector-%s" $root.Release.Name $pool | trunc 63 | trimSuffix "-" }}
  labels:
    service: trapcollector
    pool: {{ $pool }}
{{ include "noc.labels" $root | indent 4 }}
spec:
  ports:
    - name: http
      port: 1200
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "noc.name" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    service: trapcollector
    pool: {{ $pool }}
{{ end }}
{{ end }}
