---
apiVersion: v1
kind: ConfigMap
metadata:
  name: front-nginx-configmap
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user '
                          '[$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        include /etc/nginx/conf.d/hc.conf;
        include /etc/nginx/conf.d/noc.conf;
        include /etc/nginx/upstream.conf;
    }
  hc.conf: |-
    server {
        # Healthcheck
        listen 81;

        location /ng_stats {
            stub_status;
            access_log off;
        }
    }
  upstream.conf: |-
    upstream web {
      server {{ template "noc.web.fullname" . }}:1200 weight=1 max_fails=3 fail_timeout=10;
    }

    upstream login {
      server {{ template "noc.login.fullname" . }}:1200 weight=1 max_fails=3 fail_timeout=10;
    }

    upstream card {
      server {{ template "noc.card.fullname" . }}:1200 weight=1 max_fails=3 fail_timeout=10;
    }

    upstream datastream {
      server {{ template "noc.datastream.fullname" . }}:1200 weight=1 max_fails=3 fail_timeout=10;
    }

    upstream nbi {
      server {{ template "noc.nbi.fullname" . }}:1200 weight=1 max_fails=3 fail_timeout=10;
    }

    upstream mrt {
      server {{ template "noc.mrt.fullname" . }}:1200 weight=1 max_fails=3 fail_timeout=10;
    }

    upstream bi {
      server {{ template "noc.bi.fullname" . }}:1200 weight=1 max_fails=3 fail_timeout=10;
    }

    upstream grafana {
      server {{ template "noc.login.fullname" . }}:1200 weight=1 max_fails=3 fail_timeout=10;
    }

    upstream grafanads {
      server {{ template "noc.grafanads.fullname" . }}:1200 weight=1 max_fails=3 fail_timeout=10;
    }
  noc.conf: |-
    server {
        listen 80 default_server reuseport;
        server_name _;

        client_max_body_size 32m;

        gzip on;
        gzip_vary on;
        gzip_comp_level 3;
        gzip_types text/html;
        gzip_types text/json;
        gzip_types text/css;
        gzip_types text/x-js;
        gzip_types text/javascript;
        gzip_types application/x-javascript;
        gzip_types application/json;
        gzip_types application/javascript;

        add_header Strict-Transport-Security
                  "max-age=63072000; includeSubDomains";

        add_header X-Content-Type-Options nosniff;
        add_header X-Backend-Server $upstream_addr always;
        add_header X-Front-Server $hostname always;

        proxy_set_header Remote-User $user;
        proxy_set_header Remote-Groups $groups;
        proxy_set_header Host $http_host;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        # Proxy authentication settings
        error_page 401 = @error401;

        location @error401 {
            return 302 /api/login/index.html?uri=$request_uri;
        }

        # Login service api
        location /api/auth/ {
            internal;
            proxy_pass http://login;
            # internal;
            gzip on;
            gzip_types text/css text/x-js;
            proxy_set_header Host $http_host;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header Content-Length '0';
        }

        # Login service api
        location /api/login/ {
            proxy_pass http://login;
            gzip on;
            gzip_types text/css text/x-js;
            proxy_set_header Host $http_host;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Original-URI $request_uri;
        }

        # Card service api
        location /api/card/ {
            proxy_pass http://card;
            auth_request /api/auth/auth/;
            # internal;
            gzip on;
            gzip_types text/css text/x-js text/json;
            proxy_set_header Host $http_host;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            auth_request_set $user $upstream_http_remote_user;
            proxy_set_header Remote-User $user;
            auth_request_set $groups $upstream_http_remote_groups;
            proxy_set_header Remote-Groups $groups;
        }

        # mrt service api
        location /api/mrt/ {
            proxy_pass http://mrt;
            proxy_read_timeout 900;
            auth_request /api/auth/auth/;
            # internal;
            gzip on;
            gzip_types text/css text/x-js text/json;
            proxy_set_header Host $http_host;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            auth_request_set $user $upstream_http_remote_user;
            proxy_set_header Remote-User $user;
            auth_request_set $groups $upstream_http_remote_groups;
            proxy_set_header Remote-Groups $groups;
        }

        # bi service api
        location /api/bi/ {
            proxy_pass http://bi;
            auth_request /api/auth/auth/;
            # internal;
            gzip on;
            gzip_types text/css text/x-js text/json;
            proxy_set_header Host $http_host;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            auth_request_set $user $upstream_http_remote_user;
            proxy_set_header Remote-User $user;
            auth_request_set $groups $upstream_http_remote_groups;
            proxy_set_header Remote-Groups $groups;
        }


        # grafanads service api
        location /api/grafanads/ {
            proxy_pass http://grafanads;
            auth_request /api/auth/auth/;
            # internal;
            gzip on;
            gzip_types text/css text/x-js;
            proxy_set_header Host $http_host;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            auth_request_set $user $upstream_http_remote_user;
            proxy_set_header Remote-User $user;
            auth_request_set $groups $upstream_http_remote_groups;
            proxy_set_header Remote-Groups $groups;
        }


        # datastream service api
        location /api/datastream/ {
            proxy_pass http://datastream;
            auth_request /api/auth/auth/;
            gzip on;
            gzip_types text/css text/x-js text/json;
            proxy_set_header Host $http_host;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            auth_request_set $apiaccess $upstream_http_x_noc_api_access;
            proxy_set_header X-NOC-API-Access $apiaccess;
        }


        location /ui/grafana {
            proxy_pass http://grafana;
            auth_request /api/auth/auth/;
            rewrite  ^/ui/grafana/(.*)  /$1 break;
            proxy_set_header Host $http_host;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            auth_request_set $user $upstream_http_remote_user;
            proxy_set_header Remote-User $user;
            auth_request_set $groups $upstream_http_remote_groups;
            proxy_set_header Remote-Groups $groups;
            proxy_set_header Authorization "";
        }

        location / {
            rewrite ^/$ /main/desktop/;
            proxy_pass http://web;
            auth_request /api/auth/auth/;
            gzip on;
            gzip_types text/css text/x-js text/json;
            proxy_set_header Host $http_host;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            auth_request_set $user $upstream_http_remote_user;
            proxy_set_header Remote-User $user;
            auth_request_set $groups $upstream_http_remote_groups;
            proxy_set_header Remote-Groups $groups;
        }
    }

  mime.types: |-
    types {
      text/html                                        html htm shtml;
      text/css                                         css;
      text/xml                                         xml;
      image/gif                                        gif;
      image/jpeg                                       jpeg jpg;
      application/javascript                           js;
      application/atom+xml                             atom;
      application/rss+xml                              rss;

      text/mathml                                      mml;
      text/plain                                       txt;
      text/vnd.sun.j2me.app-descriptor                 jad;
      text/vnd.wap.wml                                 wml;
      text/x-component                                 htc;

      image/png                                        png;
      image/svg+xml                                    svg svgz;
      image/tiff                                       tif tiff;
      image/vnd.wap.wbmp                               wbmp;
      image/webp                                       webp;
      image/x-icon                                     ico;
      image/x-jng                                      jng;
      image/x-ms-bmp                                   bmp;

      font/woff                                        woff;
      font/woff2                                       woff2;

      application/java-archive                         jar war ear;
      application/json                                 json;
      application/mac-binhex40                         hqx;
      application/msword                               doc;
      application/pdf                                  pdf;
      application/postscript                           ps eps ai;
      application/rtf                                  rtf;
      application/vnd.apple.mpegurl                    m3u8;
      application/vnd.google-earth.kml+xml             kml;
      application/vnd.google-earth.kmz                 kmz;
      application/vnd.ms-excel                         xls;
      application/vnd.ms-fontobject                    eot;
      application/vnd.ms-powerpoint                    ppt;
      application/vnd.oasis.opendocument.graphics      odg;
      application/vnd.oasis.opendocument.presentation  odp;
      application/vnd.oasis.opendocument.spreadsheet   ods;
      application/vnd.oasis.opendocument.text          odt;
      application/vnd.openxmlformats-officedocument.presentationml.presentation
                                                       pptx;
      application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                                                       xlsx;
      application/vnd.openxmlformats-officedocument.wordprocessingml.document
                                                       docx;
      application/vnd.wap.wmlc                         wmlc;
      application/x-7z-compressed                      7z;
      application/x-cocoa                              cco;
      application/x-java-archive-diff                  jardiff;
      application/x-java-jnlp-file                     jnlp;
      application/x-makeself                           run;
      application/x-perl                               pl pm;
      application/x-pilot                              prc pdb;
      application/x-rar-compressed                     rar;
      application/x-redhat-package-manager             rpm;
      application/x-sea                                sea;
      application/x-shockwave-flash                    swf;
      application/x-stuffit                            sit;
      application/x-tcl                                tcl tk;
      application/x-x509-ca-cert                       der pem crt;
      application/x-xpinstall                          xpi;
      application/xhtml+xml                            xhtml;
      application/xspf+xml                             xspf;
      application/zip                                  zip;

      application/octet-stream                         bin exe dll;
      application/octet-stream                         deb;
      application/octet-stream                         dmg;
      application/octet-stream                         iso img;
      application/octet-stream                         msi msp msm;

      audio/midi                                       mid midi kar;
      audio/mpeg                                       mp3;
      audio/ogg                                        ogg;
      audio/x-m4a                                      m4a;
      audio/x-realaudio                                ra;

      video/3gpp                                       3gpp 3gp;
      video/mp2t                                       ts;
      video/mp4                                        mp4;
      video/mpeg                                       mpeg mpg;
      video/quicktime                                  mov;
      video/webm                                       webm;
      video/x-flv                                      flv;
      video/x-m4v                                      m4v;
      video/x-mng                                      mng;
      video/x-ms-asf                                   asx asf;
      video/x-ms-wmv                                   wmv;
      video/x-msvideo                                  avi;
    }
