---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-noc-secret
type: Opaque
stringData:
  NOC_CLICKHOUSE_RW_USER: '{{ .Values.clickhouse.users.rw_user_name }}'
  NOC_CLICKHOUSE_RW_PASSWORD: '{{ .Values.clickhouse.users.rw_user_password }}'
  NOC_CLICKHOUSE_RO_USER: '{{ .Values.clickhouse.users.ro_user_name }}'
  NOC_CLICKHOUSE_RO_PASSWORD: '{{ .Values.clickhouse.users.ro_user_password }}'
  NOC_MONGO_USER: '{{ .Values.mongodb.mongodbUsername }}'
  NOC_MONGO_PASSWORD: '{{ .Values.mongodb.mongodbUsername }}'
  NOC_PG_USER: '{{ .Values.postgresql.postgresqlUsername }}'
  NOC_PG_PASSWORD: '{{ .Values.postgresql.postgresqlPassword }}'
  NOC_PG_DB: '{{ .Values.postgresql.postgresqlDatabase }}'

