---
apiVersion: v1
kind: ConfigMap
metadata:
  name: noc-configmap
data:
  NOC_CONSUL_HOST: '{{ .Release.Name }}-consul-server'
  NOC_CLICKHOUSE_RO_ADDRESSES: '{{ .Release.Name }}-clickhouse:8123'
  NOC_CLICKHOUSE_RW_ADDRESSES: '{{ .Release.Name }}-clickhouse:8123'
  NOC_CONFIG: 'env:///NOC'
  NOC_FEATURES_CONSUL_HEALTHCHECKS: 'true'
  NOC_FEATURES_CP: 'false'
  NOC_FEATURES_SERVICE_REGISTRATION: 'true'
  NOC_LISTEN: 'auto:1200'
  NOC_MONGO_ADDRESSES: '{{ .Release.Name }}-mongodb:27017'
  NOC_NSQD_ADDRESSES: '{{ .Release.Name }}-nsqd:4150'
  NOC_NSQD_HTTP_ADDRESSES: '{{ .Release.Name }}-nsqd:4151'
  NOC_NSQLOOKUPD_ADDRESSES: '{{ .Release.Name }}-lookupd:4160'
  NOC_NSQLOOKUPD_HTTP_ADDRESSES: '{{ .Release.Name }}-lookupd:4161'
  NOC_PG_ADDRESSES: '{{ .Release.Name }}-postgresql:5432'
  NOC_PG_DB: '{{ .Values.postgresql.postgresDatabase }}'
{{ .Values.nocExtraConfiguration | indent 2 }}
